#!/usr/bin/env node
// render-openapi.mjs — emit ./openapi.json (OpenAPI 3.1) from .backend-design/state/*.json.
//
// Same pattern as render-design.mjs / render-env-example.mjs: pure deterministic emitter,
// idempotent, additive — running it doesn't touch any other artifact. Codegen stacks then
// copy this file into the scaffolded backend so the Swagger UI at /docs serves the same
// design-time contract that backend-design.md describes.

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";
import { isMainModule } from "./is-main.mjs";

const OUTPUT_FILE = "openapi.json";
const STATE_FILES = ["endpoints.json", "entities.json", "auth.json"];

// Maps entities.json type names to OpenAPI 3.1 schema fragments. Unknown types fall through
// to { type: "string" } so spec generation never crashes on a hand-edited entity.
const TYPE_MAP = {
  uuid: { type: "string", format: "uuid" },
  text: { type: "string" },
  string: { type: "string" },
  varchar: { type: "string" },
  int: { type: "integer" },
  integer: { type: "integer" },
  bigint: { type: "integer", format: "int64" },
  smallint: { type: "integer" },
  serial: { type: "integer" },
  float: { type: "number" },
  double: { type: "number" },
  decimal: { type: "number" },
  numeric: { type: "number" },
  boolean: { type: "boolean" },
  bool: { type: "boolean" },
  timestamptz: { type: "string", format: "date-time" },
  timestamp: { type: "string", format: "date-time" },
  date: { type: "string", format: "date" },
  jsonb: { type: "object" },
  json: { type: "object" },
};

export function renderOpenApi(cwd = process.cwd()) {
  const state = loadState(cwd);
  const config = loadJson(join(cwd, ".backend-design", "config.json")) ?? {};
  const userPkg = loadJson(join(cwd, "package.json")) ?? {};

  const endpoints = (state.endpoints ?? []).filter(
    (ep) => ep && !ep.is_external && !ep.temporary
  );
  const realEndpoints = endpoints.filter((ep) => !ep.is_webhook);
  const webhookEndpoints = endpoints.filter((ep) => ep.is_webhook);

  const spec = {
    openapi: "3.1.0",
    info: buildInfo(config, userPkg),
    servers: buildServers(),
    paths: buildPaths(realEndpoints, state),
    webhooks: buildWebhooks(webhookEndpoints, state),
    components: buildComponents(state),
    tags: buildTags(realEndpoints),
  };

  // Strip empty top-level objects so the spec stays clean.
  if (!Object.keys(spec.webhooks).length) delete spec.webhooks;
  if (!spec.tags.length) delete spec.tags;
  if (!Object.keys(spec.components.schemas).length && !Object.keys(spec.components.securitySchemes).length) {
    delete spec.components;
  }
  return spec;
}

function buildInfo(config, userPkg) {
  const framework = config?.frontend?.framework ?? "App";
  const version = typeof userPkg.version === "string" ? userPkg.version : "0.1.0";
  return {
    title: `${framework} backend`,
    version,
    description:
      "Generated by backend-design from .backend-design/state/. Edit the state JSON and re-run `node <SKILL_DIR>/scripts/render-openapi.mjs` to regenerate.",
  };
}

function buildServers() {
  return [{ url: "http://localhost:3000", description: "local dev" }];
}

function buildPaths(endpoints, state) {
  const paths = {};
  for (const ep of endpoints) {
    if (!ep.method || !ep.path) continue;
    const openapiPath = colonToBrace(ep.path);
    const method = ep.method.toLowerCase();
    if (!paths[openapiPath]) paths[openapiPath] = {};
    paths[openapiPath][method] = buildOperation(ep, state);
  }
  return paths;
}

function buildOperation(ep, state) {
  const op = {
    summary: defaultSummary(ep),
    tags: [tagFor(ep.path)],
    operationId: operationId(ep),
  };

  const parameters = buildParameters(ep);
  if (parameters.length) op.parameters = parameters;

  const requestBody = buildRequestBody(ep);
  if (requestBody) op.requestBody = requestBody;

  op.responses = buildResponses(ep, state);

  if (ep.auth === "required" && state.auth?.strategy === "jwt") {
    op.security = [{ bearerAuth: [] }];
  }
  if (ep.required_role) {
    op["x-required-role"] = Array.isArray(ep.required_role) ? ep.required_role : [ep.required_role];
  }
  if (ep.inferred_from_signal) {
    op["x-inferred-from-signal"] = ep.inferred_from_signal;
  }
  return op;
}

function buildParameters(ep) {
  const params = [];

  for (const pp of ep.path_params ?? []) {
    if (!pp?.name) continue;
    params.push({
      name: pp.name,
      in: "path",
      required: true,
      schema: mapType(pp.type ?? "string"),
      ...(pp.parent_entity ? { description: `Scopes the query to ${pp.parent_entity}.` } : {}),
    });
  }

  // Implicit :id from a trailing /<thing>/:id when not declared in path_params.
  const trailingMatch = (ep.path ?? "").match(/\/:([a-zA-Z_][a-zA-Z0-9_]*)$/);
  if (trailingMatch) {
    const trailingName = trailingMatch[1];
    if (!params.some((p) => p.name === trailingName)) {
      params.push({
        name: trailingName,
        in: "path",
        required: true,
        schema: { type: "string" },
      });
    }
  }

  for (const f of ep.filterable_fields ?? []) {
    params.push({
      name: f,
      in: "query",
      required: false,
      schema: { type: "string" },
      description: "Filter results by exact match.",
    });
  }

  if (ep.sortable_fields?.length) {
    params.push({
      name: "sort",
      in: "query",
      required: false,
      schema: {
        type: "string",
        pattern: `^(${ep.sortable_fields.join("|")}):(asc|desc)$`,
      },
      description: `Sort field and direction. Allowed: ${ep.sortable_fields.join(", ")}.`,
    });
  }

  const strategy = ep.pagination?.strategy;
  if (strategy === "cursor") {
    params.push({ name: "cursor", in: "query", required: false, schema: { type: "string" } });
    params.push({ name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } });
  } else if (strategy === "offset") {
    params.push({ name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0, default: 0 } });
    params.push({ name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } });
  }

  return params;
}

function buildRequestBody(ep) {
  const body = ep.request_body;
  if (!body || typeof body !== "object" || !Object.keys(body).length) return null;

  if (ep.content_type === "multipart/form-data") {
    const properties = {};
    const required = [];
    for (const [name, def] of Object.entries(body)) {
      if (def && typeof def === "object" && def.accept !== undefined) {
        properties[name] = { type: "string", format: "binary" };
      } else {
        properties[name] = mapType(typeof def === "string" ? def : "string");
      }
      required.push(name);
    }
    return {
      required: true,
      content: {
        "multipart/form-data": {
          schema: { type: "object", properties, required },
        },
      },
    };
  }

  const properties = {};
  const required = [];
  for (const [name, def] of Object.entries(body)) {
    properties[name] = mapType(typeof def === "string" ? def : "string");
    required.push(name);
  }
  return {
    required: true,
    content: {
      "application/json": {
        schema: { type: "object", properties, required },
      },
    },
  };
}

function buildResponses(ep, state) {
  const method = (ep.method ?? "").toUpperCase();
  const responses = {};

  if (method === "DELETE") {
    responses["204"] = { description: "Deleted." };
  } else {
    const status = method === "POST" ? "201" : "200";
    const schema = responseSchema(ep, state);
    if (schema) {
      responses[status] = {
        description: status === "201" ? "Created." : "OK.",
        content: { "application/json": { schema } },
      };
    } else {
      responses[status] = { description: status === "201" ? "Created." : "OK." };
    }
  }

  if (ep.request_body && Object.keys(ep.request_body).length) {
    responses["400"] = { description: "Validation error." };
  }
  if (ep.auth === "required") {
    responses["401"] = { description: "Missing or invalid credentials." };
  }
  if (ep.required_role) {
    responses["403"] = { description: "Authenticated but not authorized for this role." };
  }
  if (method === "PATCH" || method === "PUT") {
    responses["409"] = { description: "Optimistic-lock conflict (If-Match mismatch)." };
  }

  return responses;
}

function responseSchema(ep, state) {
  const r = ep.response;
  if (r == null) return null;
  if (typeof r !== "string") return null;

  const isArray = r.endsWith("[]");
  const entityName = isArray ? r.slice(0, -2) : r;
  const hasSchema = (state.entities ?? []).some((e) => e?.name === entityName);

  if (hasSchema) {
    const ref = { $ref: `#/components/schemas/${entityName}` };
    if (!isArray) return ref;
    if (ep.pagination?.strategy === "cursor") {
      return {
        type: "object",
        properties: {
          data: { type: "array", items: ref },
          next_cursor: { type: ["string", "null"] },
        },
        required: ["data"],
      };
    }
    if (ep.pagination?.strategy === "offset") {
      return {
        type: "object",
        properties: {
          data: { type: "array", items: ref },
          total: { type: "integer" },
        },
        required: ["data", "total"],
      };
    }
    return { type: "array", items: ref };
  }

  // Fallback: response names a non-entity type (e.g. "Session", "{ ok: true }"). Emit a free
  // object so consumers don't 404 on the schema $ref.
  return isArray ? { type: "array", items: { type: "object" } } : { type: "object" };
}

function buildWebhooks(webhookEndpoints, state) {
  const webhooks = {};
  for (const ep of webhookEndpoints) {
    if (!ep.method || !ep.path) continue;
    const name = webhookName(ep);
    const method = ep.method.toLowerCase();
    const sigHeader = ep.signature_header ?? `X-${(ep.webhook_source ?? "Provider")}-Signature`;
    const source = ep.webhook_source ?? "the provider";
    webhooks[name] = {
      [method]: {
        summary: `Incoming ${source} webhook`,
        description:
          `Sent by ${source} to ${ep.path}. The handler verifies the \`${sigHeader}\` header against ` +
          `\`${(source || "PROVIDER").toUpperCase()}_WEBHOOK_SECRET\` before processing. ` +
          `See the provider's webhook docs for the signing-secret rotation procedure.`,
        parameters: [
          {
            name: sigHeader,
            in: "header",
            required: true,
            schema: { type: "string" },
            description: `Signature header used to verify the webhook payload.`,
          },
        ],
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { type: "object", description: "Provider-defined event payload." },
            },
          },
        },
        responses: {
          "200": { description: "Webhook accepted." },
          "401": { description: "Signature verification failed." },
        },
      },
    };
  }
  return webhooks;
}

function webhookName(ep) {
  const source = (ep.webhook_source ?? "").trim();
  const slug = (ep.path ?? "")
    .replace(/^\//, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return source ? `${source}.${slug || "event"}` : slug || "incoming";
}

function buildComponents(state) {
  const schemas = {};
  for (const ent of state.entities ?? []) {
    if (!ent?.name) continue;
    schemas[ent.name] = entityToSchema(ent);
  }

  const securitySchemes = {};
  if (state.auth?.strategy === "jwt") {
    securitySchemes.bearerAuth = { type: "http", scheme: "bearer", bearerFormat: "JWT" };
  }
  // Cookie-session security scheme (added in v0.11.0). Only emit when auth.json declares it.
  if (state.auth?.strategy === "session") {
    const cookieName = state.auth?.cookie?.name ?? "sid";
    securitySchemes.cookieAuth = { type: "apiKey", in: "cookie", name: cookieName };
  }

  return { schemas, securitySchemes };
}

function entityToSchema(ent) {
  const properties = {};
  const required = [];
  for (const f of ent.fields ?? []) {
    if (!f?.name) continue;
    const schema = mapType(f.type ?? "string");

    if (f.pk) schema.readOnly = true;
    if (f.name === "version") schema.readOnly = true;
    if (f.name === "created_at" || f.name === "updated_at") schema.readOnly = true;
    if (f.name === "deleted_at") {
      schema.type = nullableType(schema.type);
      schema.readOnly = true;
    }
    if (f.name === "created_by" || f.name === "updated_by") {
      schema.type = nullableType(schema.type);
      schema.readOnly = true;
    }
    if (f.fk) schema.description = `Foreign key → \`${f.fk}\`.`;

    properties[f.name] = schema;
    if (f.required && !f.pk) required.push(f.name);
  }
  const out = { type: "object", properties };
  if (required.length) out.required = required;
  return out;
}

function buildTags(endpoints) {
  const seen = new Set();
  const out = [];
  for (const ep of endpoints) {
    const tag = tagFor(ep.path);
    if (seen.has(tag)) continue;
    seen.add(tag);
    out.push({ name: tag });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

function tagFor(path) {
  if (!path) return "default";
  const segments = path.split("/").filter(Boolean);
  // Skip a leading "api" prefix if present so /api/users and /users group together.
  const first = segments[0] === "api" ? segments[1] : segments[0];
  return first ?? "default";
}

function defaultSummary(ep) {
  const method = (ep.method ?? "").toUpperCase();
  const path = ep.path ?? "";
  return `${method} ${path}`;
}

function operationId(ep) {
  const method = (ep.method ?? "get").toLowerCase();
  const slug = (ep.path ?? "")
    .replace(/^\//, "")
    .replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, "by_$1")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${method}_${slug || "root"}`;
}

function colonToBrace(path) {
  return (path ?? "").replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, "{$1}");
}

function mapType(typeName) {
  const key = String(typeName ?? "").toLowerCase();
  // Clone — callers mutate (readOnly, nullable) on the returned object.
  const hit = TYPE_MAP[key];
  return hit ? { ...hit } : { type: "string" };
}

function nullableType(t) {
  if (Array.isArray(t)) return t.includes("null") ? t : [...t, "null"];
  return [t, "null"];
}

function loadState(cwd) {
  const dir = join(cwd, ".backend-design", "state");
  const out = {};
  for (const f of STATE_FILES) {
    const p = join(dir, f);
    if (!existsSync(p)) continue;
    try {
      out[f.replace(".json", "")] = JSON.parse(readFileSync(p, "utf8"));
    } catch {
      // Validator surfaces parse errors elsewhere.
    }
  }
  return out;
}

function loadJson(path) {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

export function summarizeSpec(spec) {
  const paths = Object.keys(spec.paths ?? {}).length;
  const operations = Object.values(spec.paths ?? {}).reduce(
    (n, item) => n + Object.keys(item ?? {}).filter((k) => !k.startsWith("x-")).length,
    0
  );
  const webhooks = Object.keys(spec.webhooks ?? {}).length;
  const schemas = Object.keys(spec.components?.schemas ?? {}).length;
  return { paths, operations, webhooks, schemas };
}

export function runRender(cwd = process.cwd()) {
  const config = loadJson(join(cwd, ".backend-design", "config.json")) ?? {};
  if (config?.stack?.id === "s2ai-schema") return null;
  const spec = renderOpenApi(cwd);
  writeFileSync(join(cwd, OUTPUT_FILE), JSON.stringify(spec, null, 2) + "\n");
  return spec;
}

if (isMainModule(import.meta.url)) {
  const spec = runRender();
  if (spec === null) {
    console.log(`Skipped ${OUTPUT_FILE} (s2ai-schema stack has no API to document).`);
  } else {
    const s = summarizeSpec(spec);
    console.log(`Wrote ./${OUTPUT_FILE} (${s.paths} paths, ${s.operations} ops, ${s.webhooks} webhooks, ${s.schemas} schemas).`);
  }
}
